# Generated by Django 3.0.5 on 2020-05-23 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publisher', '0002_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
