# Generated by Django 3.0.5 on 2020-05-23 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publisher', '0003_auto_20200523_0259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=4)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
