# Generated by Django 3.0.5 on 2020-05-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publisher', '0006_auto_20200526_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='sended',
            name='checker_url',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='sended',
            name='content',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='sended',
            name='date',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='sended',
            name='user_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sended',
            name='user_screen_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sended',
            name='channel',
            field=models.CharField(default='twitter', max_length=100),
        ),
        migrations.AlterField(
            model_name='sended',
            name='img_url',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='sended',
            name='status_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
