# Generated by Django 3.0.5 on 2020-05-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publisher', '0007_auto_20200526_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sended',
            name='email',
            field=models.CharField(default='', max_length=300),
        ),
    ]
